name: vector-sized
version: 1.4.3.1
synopsis: Size tagged vectors
description: Please see README.md
category: Data
author: Joe Hermaszewski
maintainer: whats.our.vector.victor@monoid.al
copyright: 2016 Joe Hermaszewski
license: BSD3
github: expipiplus1/vector-sized

extra-source-files:
- package.yaml
- readme.md
- changelog.md
- default.nix

dependencies:
- base >=4.9 && <5
- vector >=0.11 && <0.13
- deepseq >=1.1 && <1.5
- finite-typelits >=0.1
- primitive >=0.5 && <0.8
- indexed-list-literals >=0.2.0.0
- adjunctions >=4.3 && <4.5
- distributive >=0.5 && <0.7
- comonad >=4 && <6
- hashable >=1.2.4.0
- binary >=0.8.3.0

library:
  source-dirs: src
